send_joint_trajectory:
  ros__parameters:
    joints: ["joint1","joint2","joint3","joint4","joint5","joint6"]
    target: [0.0, 0.0, 90.0, 0.0, 0.0, 0.0]   # DEGREES
    duration: 2.0
    base_frame: "base_link"
    tip_frame: "link6"