send_pose_trajectory:
  ros__parameters:
    controller_name: arm_controller
    joint_names: [joint1, joint2, joint3, joint4, joint5, joint6]

    # Target pose in BASE_LINK frame
    target_xyz: [0.4, 0.00, 0.5]
    target_rpy_deg: [0.0, 180.0, 0.0]   # Degrees

    # Geometry (match xacro defaults)
    L1: 0.4
    L2: 0.4318
    L3: 0.43208
    d3: 0.1397 #d3: 0.0
    
    elbow: up
    wrist: noflip

    solve_orientation: true #true/false
    duration_sec: 10.0
    wait_result: true

    base_link: base_link
    tip_link: link6
    tf_timeout_sec: 2.0
