send_pose_trajectory:
  ros__parameters:
    controller_name: arm_controller
    joint_names: [joint1, joint2, joint3, joint4, joint5, joint6]

    # Target pose in BASE_LINK frame
    target_xyz: [0.45, 0.00, 0.5]
    target_rpy_deg: [0.0, -90.0, 0.0]   # Degrees

    # Geometry (match xacro defaults)
    L1: 0.4
    L2: 0.4318
    L3: 0.43208
    d3: 0.1397 #d3: 0.0
    
    elbow: up
    wrist: noflip

    #Njoint_lower_deg: [-160, -180, -45, -150, -100, -266]
    #joint_upper_deg: [ 160,  70,  220,  150,  100,  266]
    joint_lower_deg: [-160, -180, -220, -150, -100, -266]
    joint_upper_deg: [ 160,  70,  240,  150,  100,  266]

    solve_orientation: true #true/false
    duration_sec: 10.0
    wait_result: true

    base_link: base_link
    tip_link: link6
    tf_timeout_sec: 2.0
