send_pose_trajectory:
  ros__parameters:
    controller_name: arm_controller
    joint_names: [joint1, joint2, joint3, joint4, joint5, joint6]

    # Target pose in WORLD frame (same frame you use to command)
    target_xyz: [0.4, 0.00, 0.6]
    target_rpy: [0.0, 90.0, 0.0] # Degrees

    # Geometry (match xacro defaults)
    base_z: 0.02
    L1: 0.4
    L2: 0.4318
    L3: 0.43208
    d3: 0.1397

    # Explicit branch selection (NO auto)
    elbow: down        # up | down
    wrist: noflip      # noflip | flip

    solve_orientation: true
    duration_sec: 2.0
    wait_result: true
